{% set name = "python-json-logger" %}
{% set version = "0.1.8" %}
{% set sha256 = "8205cfe7061715de5cd1b37e3565d5b97d0ac13b30ff3ee612554abb6093d640" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pythonjsonlogger

about:
  home: http://github.com/madzak/python-json-logger
  license_file: LICENSE
  license: BSD 2-clause
  license_family: BSD
  summary: 'A python library adding a json log formatter'
  description: |
      This library is provided to allow standard python logging to output log
      data as json objects. With JSON we can make our logs more readable by
      machines and we can stop writing custom parsers for syslog type records.

extra:
  recipe-maintainers:
    - sodre
    - ukaratay
