{% set name = "python-json-logger" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23e7ec02d34237c5aa1e29a070193a4ea87583bb4e7f8fd06d3de8264c4b2e1c

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed . -vv

requirements:
  build:
    - python
    - pip
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pythonjsonlogger
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/madzak/python-json-logger
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: 'A python library adding a json log formatter'
  description: |
      This library is provided to allow standard python logging to output log
      data as json objects. With JSON we can make our logs more readable by
      machines and we can stop writing custom parsers for syslog type records.
  dev_url: https://github.com/madzak/python-json-logger
  doc_url: https://github.com/madzak/python-json-logger/blob/master/README.md

extra:
  recipe-maintainers:
    - sodre
    - ukaratay
