{% set name = "python-json-logger" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_json_logger-{{ version }}.tar.gz
  sha256: 8eb0554ea17cb75b05d2848bc14fb02fbdbd9d6972120781b974380bfa162008

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed . -vv

requirements:
  build:
    - python
    - pip
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions  # [py<310]

test:
  imports:
    - pythonjsonlogger
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://nhairs.github.io/python-json-logger/latest
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: 'JSON Formatter for Python Logging'
  description: |
    Python JSON Logger enables you produce JSON logs when using Python's logging package.

    JSON logs are machine readable allowing for much easier parsing and ingestion into log aggregation tools.
  dev_url: https://github.com/nhairs/python-json-logger
  doc_url: https://nhairs.github.io/python-json-logger/latest

extra:
  recipe-maintainers:
    - sodre
    - ukaratay
