travis:
  secure:
    BINSTAR_TOKEN: Ov5GlyeeJ+7MF8XM0DtSdnoxmEpRLNJKhL2ov+JhSL5EpZ6tjfpmheM13iXEPX2Z38KI3O8Qws5VkY3lZIhRdaZggaWx6TSUxV60dh/Gfu2IQcThRVwCrrTTJBpQ57MtjJ/NIwfqvMbNapTVLvqrinZ3aMpGhuWddrr8IFz2Qa0D48KXGTNkFURLfgZrBsrrAhuFJIn0Q7SwUbh2qmwuYLo8/DpeLqJwVldPpNxJUf6ITt1CylvUFKmF1EtSvcaE1kTjYQFqaoSzBhmuvL/elt0K1RBT26zfsFVSdf0GyR91TyKoGeK64KawQ1vb3bLHMqCQUNFRP5N/VLyN9OXVVw3RzXPktOqQbHHzRZTkHWJPSUoR6/Yh3lHbNu3eGC3qSFRZCZOTco1mmsssapKWNM2dhDt1Rw8ZUQgYlgMAP4Vc/18RWTFZ4hjDwvgt9Zx9bIF+Rg/WmBVGpTDM45rHYw8KFyOktd/6+s1g+SBXdp+mGt/E2POkNoDjqmvm/H/AVZIiswEFdDwGizxRD7UZ9AB/FHdk/FM37AzyB/kQAmCyTuscUU+PDKVCgiA6eDV1uC9vzycOgoYZIFpEW0KyDHiDrc6iqCoL/3gMe2aM92u7XZEyNHCPhgxGZRCgPWp8tZsZKwAMYMxTc8CunRm/58Mz2rog437fYMfOQNOJlq8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
