travis:
  secure:
    BINSTAR_TOKEN: buorCeHb+tXgj8oKugqKSpcPsNtRqupjHHuO3HeMV4r+imjxzDK1lM6blrtT+obh84I/ZUOyA+xSopiLVcpeg5o+sWrBBtyL8tYUCUWlzVN+hq0lwSl93oAewqPplmfapmws37iSM8Ufuk2z2GoaHGALkkA4YNoWkyNhzufEZPNphTd4VuUvG1AxgbXiiIrN8BfsX2UMWbMp7FkcxvoK5QiK8qQTeESOM8qHBBqbHncO/NPvdqkFuyJa/XgR5u6pEbIdKwt+nWxfiXtb3hgfz0uScqQLbT5W/yAnCK5jtTf2V1tSQl/oOS4xx6Ok/jNOe49XjVcZwLUf2BlVd1SeYSAt/ozG5FrEv9WRW6kzpYueUKvwhVtg2Dyv8qdKQ63f5gB2GARpAYBLG9e5Fip0bEi9mPgAoFbcT6tmYxtO2JkkGazZxT4WL5dmg/p7YNWHm0BZQITx16WKzZnKADoh36ryDRPQTmkpAbeW7zh52gKS1wKga9CHHi02EcZlONcGN1YSorICcqc/fTUj6FPacxYXrce13lEXZKPR/Dgz1S0bnYdNdY8HiIjyz8V7JWxAV/PKAZV6c8GC0Wkdth4dvEDFWxYuNVtDjk20Fcv15VM9GH8ki8fmMSH3jUGYWjP5/bDFF0r7uBEH76ZQncLEfQriVRGrl2kkknuLw2wGH9k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
