travis:
  secure:
    BINSTAR_TOKEN: sGQWXJbTkVxzMkVRubfAW7B/8tmbe72SatAJGqpKhBCqSOAAy9yXsP4moRdCNQOli+fRXaGOn/g16mq9UCM9bBUGYHngb67XiYVw96yFwGvcaRqHUe5s/UblFHXqg1P2vI0DYe8UXx5b88un1PX/D6H0gNeJqivLl4+7ZoJaPUd9+SL8l7AmNe3comYQZL4ucifm1lZHXEwGfxnTg3sSvDWbTFtA75xJlAO+jAiLdeNit1HCj+ZxranYDev/1/Igi5Z/HVpigELm/IpspywILbUUtiPlbNvM3JlwqgMY6OJnP6Ji7gdy5OkaNYBLP6lpe5mJjU9Ejbx/PRkV25miCDqw0SNPD8uC2R3Zm5RwDxW9SnxW9JxcK/tzeRlmLb/wmcSwGvMSQvIXdmkygqakhbqVlzX0FNeWVzs5wIeY1pzH9R8cUzPVON+iv252xIFpjGQCiQSBAZBuxApvNO/nCWTN46Sr+hbX6+pu5KNuJz2NRKbXdov/XD/95c0InTyavF1RIJc8nOvKX3b8EdXwUtGeFApv1LjwxTVUCKNNIlyQIkIL8B59r3pNZyQwF9YtCiBwSa4kV1dCWrwzS2JUZOdvxgMDrcJwn7TvinyeAWmKxfUfpR76/U8AJg6ZOBsWrs6LskwgLA+CzNm2jINB6dRjwPL5BjXbHl13VWp4yLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
